export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
} as const;

export const DATABASE_TIMEOUTS = {
  MAX_POOL_SIZE: 10,
  MIN_POOL_SIZE: 1,
  MAX_IDLE_TIME_MS: 30000,
  SERVER_SELECTION_TIMEOUT_MS: 5000,
  SOCKET_TIMEOUT_MS: 45000,
  CONNECT_TIMEOUT_MS: 10000,
} as const;

export const VALIDATION = {
  MAX_NAME_LENGTH: 50,
  MAX_CODE_LENGTH: 10,
  MAX_DESCRIPTION_LENGTH: 500,
  MAX_RESOURCE_NAME_LENGTH: 100,
  MAX_RESOURCE_IDENTIFIER_LENGTH: 100,
  MAX_ROLE_ORDER: 999999,
  MIN_PASSWORD_LENGTH: 8,
} as const;

export const HIERARCHY = {
  MAX_LEVEL: 10,
  MIN_LEVEL: 1,
  DEFAULT_ORDER: 0,
} as const;

export const CONNECTION_STATES = {
  DISCONNECTED: 0,
  CONNECTED: 1,
  CONNECTING: 2,
  DISCONNECTING: 3,
} as const;
